import OpportunityTable from "@/components/OpportunityTable";
import { demoOpportunities } from "@/lib/demo";
import { getSupabaseAdmin } from "@/lib/supabase";
export const dynamic="force-dynamic";
export default async function Home(){
  const supabase=getSupabaseAdmin();
  let items=demoOpportunities;
  if(supabase){const {data}=await supabase.from("opportunities").select("*").order("opportunity_score",{ascending:false}).limit(100);if(data?.length)items=data;}
  const high=items.filter(x=>x.opportunity_score>=70).length;
  const dissolved=items.filter(x=>x.company_status?.toLowerCase().includes("dissolved")).length;
  return <main className="shell"><div className="topbar"><div className="brand">Land Opportunity Finder</div><div className="toolbar"><a className="tiny" href="/sources">Source registry</a><span className="badge">Hertsmere MVP</span></div></div><section className="hero"><div className="panel"><h1>Find land and property opportunities others miss.</h1><p className="lead">An evidence-led AI research agent that combines ownership, corporate, planning, vacancy, access and constraint signals into an actionable acquisition shortlist.</p></div><div className="panel metrics"><div className="metric"><strong>{items.length}</strong><span>leads ranked</span></div><div className="metric"><strong>{high}</strong><span>high-potential</span></div><div className="metric"><strong>{dissolved}</strong><span>dissolved-company leads</span></div></div></section><OpportunityTable items={items}/><section className="grid2" style={{marginTop:18}}><div className="panel"><h2>What makes this different</h2><p className="tiny">The platform stores evidence and provenance, not just addresses. Every lead should explain why it is interesting, how confident the system is, what could prevent development, and the lawful route to approach or acquisition.</p></div><div className="panel"><h2>Next ingestion sequence</h2><div className="signals"><span className="signal">HMLR INSPIRE polygons</span><span className="signal">Hertsmere brownfield register</span><span className="signal">Planning applications</span><span className="signal">Corporate proprietors</span><span className="signal">Companies House</span><span className="signal">Council assets</span><span className="signal">Flood & constraints</span></div></div></section></main>}
